application:
  blacklist-api:
    url: http://localhost:8081/blacklist
  queues:
    producer:
      collaborator-url: 'aws2-sqs://test1'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  redis:
    host: 'localhost'
    timeout: 10000
  cache:
    redis:
      time-to-live: 300s
      use-key-prefix: true
    type: redis
  #spring
  jpa:
    show-sql: true

camel:
  component:
    aws2-sqs:
      proxy-host: 'localhost'
      proxy-port: 4566
      region: 'us-east-1'
      protocol: 'http'