spring:
  blacklist-api:
  url: http://localhost:8081/blacklist
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
#spring
  jpa:
    show-sql: true
